### ISSUE TITLE
When "hidden", blank icon appears

### ISSUE THREAD

**Issue by yochananmarqos** [Trsnaqe/gamemode-shell-extension#2]
Regarding #1 with V9.0, with the option to hide the icon when not active, it displays a blank icon until toggled again.

GNOME 46.3
Manjaro GNOME (unstable branch)

**Comment by Trsnaqe** [comment]
I can't replicate the black box issue; however, I have encountered another issue that might be related. The icon doesn't reappear when setting the visibility back to visible, which may indicate some incorrect API usage. This fixes that.

Please remove current build, install this extension after extracting with `./makezip.sh install`.
Restart shell or restart os and please try it out again. 
Thanks!
[gamemodeshellextension@trsnaqe.com.shell-extension.zip](https://github.com/user-attachments/files/16117579/gamemodeshellextension%40trsnaqe.com.shell-extension.zip)

**Comment by yochananmarqos** [comment]
Applying ddfdeeb worked, thanks!

**Comment by Trsnaqe** [comment]
I have just updated the extension on the EGO. You can switch back to the stable version. Thank you for reporting the issue; I would not have discovered this bug otherwise, as I do not use that specific scenario myself.

[Stable](https://extensions.gnome.org/extension/7074/gamemode-shell-extension/) 

Thanks again for reporting the issue!
